Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"

  config.vm.provider "virtualbox" do |v|
		v.memory = 1024
		v.cpus = 1
	end

  config.vm.define "userSM" do |master|
  master.vm.hostname = "userSM"
  master.vm.network :private_network, ip: "192.168.59.140"
  master.vm.synced_folder ".", "/vagrant", type: "virtualbox"
  master.vm.provision "shell", privileged: true, path: "../scripts/install.sh"
  end
end