Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"

  config.vm.provider "virtualbox" do |v|
		v.memory = 1024
		v.cpus = 1
	end

  config.vm.define "server" do |master|
  master.vm.hostname = "server"
  master.vm.network :private_network, ip: "192.168.59.140"
  master.vm.synced_folder ".", "/vagrant", type: "virtualbox"
  master.vm.provision "shell", privileged: true, path: "scripts/install-master.sh"
  end

  config.vm.define "agent" do |worker|
  worker.vm.hostname = "agent"
  worker.vm.network :private_network, ip: "192.168.59.141" 
  worker.vm.synced_folder ".", "/vagrant", type: "virtualbox"
  worker.vm.provision "shell", privileged: true, path: "scripts/install-worker.sh"
  end
end